= Overview of alignments
:doctype: book
:icons: font
:toc: left
:toclevels: 2
:source-highlighter: coderay
:source-language: xml
:sectanchors:
:sectnums:

The alignment of the BIS specification to the EN has been done with referenct to the EN 16931 electronc invoice in line with the adoption of that standard into BIS5A Billing. The work is based on the following documents and decisions:
* Peppol invoice to EN 16931 gap analysis that formed basis for the BIS5A Billing.
https://openpeppol.atlassian.net/wiki/download/attachments/180125738/Gap%20analysis.xlsx?api=v2
* BIS3 Scope and disposition addressing how gaps identified for the invoice should be adopted into other specifications. https://openpeppol.atlassian.net/wiki/download/attachments/180125738/BIS3%20Scope%20and%20disposition.docx?api=v2
* Agreements made by the BIS3 work team members and documented in the team minutes.

An important part of the alignment work was to adopt the documentation of the BIS5A Billing to other specifications by using a browsable format instead of Word documents and spreadsheets.

Minutes and further details can be found in the project space in Confluence https://openpeppol.atlassian.net/wiki/spaces/PB3UWG/overview

An overview of the changes made as part of can be found in http://test-docs.peppol.eu/poacc/upgrade-3/changes/



