[[scope-of-invoice-response-message]]
= Scope of Invoice Response

Invoice Response is an invoice and credit note specific response message that can be used by the receiver of an invoice or credit note to inform its issuer of the status of the document in the receiver's approval and processing workflow, based on the receiver's business rules and/or a Seller/Buyer agreement.

In a standard billing process, the Buyer receives the invoice and sends the Invoice Response to the Seller. In a self-billing process, the Seller receives the self-billed invoice and sends the Invoice Response to the Buyer.

.Invoice Response will provide following benefits to its users:
* Invoice Response helps the issuer initiate an action early when processing of an invoice or credit note is challenged by the receiver.
* The response informs the issuer whether the document is being processed or whether that process is disrupted and requires action from the issuer.
* Invoice Response provides automated means for the receiver to keep the issuer informed of the document status and thus reduces or eliminates the need for manual status queries.
* Invoice Response is designed to support automatic processing on the issuer side although it still may require manual actions.
* Invoice Response structures the feedback loop from the document receiver to the document issuer.
* Invoice Response allows the document receiver to communicate decisions about document processing in a structured or unstructured form.

== In scope

.The following concepts are within the scope of the Invoice Response:
* The receiver can inform the issuer about invoice and credit note processing steps and statuses in the receiver's workflow.
* Invoice Response is based on the receiver's business rules.
* Invoice Response is a one directional message from the receiver of the referenced business document to its issuer. This is Buyer to Seller for standard billing and Seller to Buyer for self-billing.
* Several response messages can potentially be exchanged for one invoice or credit note.
* Response content may require manual action on the issuer's side.
* Invoice Response supports only push message of the invoice status.
* Invoice Response can not be automatically requested by the document issuer.
* Acknowledging that a transmitted invoice has been received and can be processed.

== Out of scope

.The following concepts are outside the scope of the Invoice Response:
* Invoice responses on a line level.
* Several statuses in one response message.
* Full automation on Seller side – not all the errors have to be encoded.
* Bi-directional communication – discussion on response.
* Enquiry of the Invoice Response.
* Transmission level status.
* Support for attachments.
