[[identification-and-dates.]]
= Identification and dates.

In the beginning of the shopping cart message there is information that identifies the shopping cart itself which allows for managing it in a processing flow as well as referencing it from other documents and processes.
This is given by an identifier as well as the date and time when the shopping cart message is created.
This would normally be the time when the buyer punches out from the sellers web store.

The identifier is created by the seller and may be of any format.
The date and time must not be in the future.

<cbc:ID>1387</cbc:ID>

<cbc:IssueDate>2016-08-01</cbc:IssueDate>

<cbc:IssueTime>09:00:00</cbc:IssueTime>

The shopping cart also includes two identifiers that identify the process that the shopping cart is used in.
The specification that define how the shopping cart message is structured and how its information shall be processed is stated with the customization ID.
This ID is always the same for all shopping cart messages that comply to this version of PEPPOL BIS 18A.
Each shopping cart messaga must comply to the specification referenced .

<cbc:CustomizationID>urn:www.cenbii.eu:transaction:biitrns077:ver2.0**:extended:** www.peppol.eu:bis:peppol18a:ver1.0</cbc:CustomizationID>



The process it self is the Punch Out process as defined in this BIS specification.
This given in the message as follows and is always the same for all message instances that comply to this version of PEPPOL BIS 18A.

<cbc:ProfileID>urn:www.cenbii.eu:profile:bii18:ver1.0</cbc:ProfileID>

Rule: ProfileID = urn:www.cenbii.eu:profile:bii18:ver1.0
