[[parties]]
= Parties

The following parties/roles may be specified in the message:

[[seller]]
== Seller

The seller is the legal person or organization acting on behalf of the supplier and who sells goods or services to the buyer.
The seller is given as the Provider Party in UBL [UBLCatalogue] and is mandatory in the PEPPOL BIS Shopping Cart message.
The seller must be identified with a name but may additionally be identified with an identifier.

The end point identifier is the PEPPOL network address [PEPPOLTransp] and the schemeID identifies the governance of the identifier used, in line with PEPPOL specifications on the use of identifiers [PEPPOLIdentifiers].

Example:

 <cac:ProviderParty>

<cbc:EndpointID schemeID="NO:ORGNR">965678996</cbc:EndpointID>

<cac:PartyIdentification>

<cbc:ID schemeID="GLN">5790000435951</cbc:ID>

</cac:PartyIdentification>

<cac:PartyName>

<cbc:Name>ABC Supplier Ltd.</cbc:Name>

</cac:PartyName>

</cac:ProviderParty>

[[buyer]]
== Buyer

The buyer is the legal person or organization acting on behalf of the customer who buys or purchases the goods or services.
The buyer is given as the ReceiverParty in UBL [UBLCatalogue] and is mandatory in the PEPPOL BIS Shopping cart message.

The endpoint identifier is the PEPPOL network address [PEPPOLTransp] and the schemeID identifies the governance of the identifier used, in line with PEPPOL specifications on the use of identifiers [PEPPOLIdentifiers]. The buyer must be identified with his name but may additionally be identified with the sellers customer identifier and/or a registered identifier.

Example:

<cac:ReceiverParty>

<cbc:EndpointID schemeID="NO:ORGNR">984661185</cbc:EndpointID>

<cac:PartyIdentification>

<cbc:ID schemeID="GLN">5790000435944</cbc:ID>

</cac:PartyIdentification>

<cac:PartyIdentification>

<cbc:ID schemeID="ZZZ">SELLERASSIGNEDID</cbc:ID>

</cac:PartyIdentification>

<cac:PartyName>

<cbc:Name>DEF Customer Ltd.</cbc:Name>

</cac:PartyName>

</cac:ReceiverParty>
