[[sellers-conditions]]
= Sellers conditions

The shopping cart allows the seller to set conditions on how the buyer may order.

The seller may set a limit of the validity time for the information in the shopping cart.
A shopping cart is valid from the time it is issued until the time stated in the validity period.
That time may not be before the time when the cart is issued.
If only validity end date is given the cart is valid until end of that day in the sellers time zone.
The seller may also set validity time for individual lines.
Validity end time is given as follows.

<cac:ValidityPeriod>

<cbc:EndDate>2016-08-31</cbc:EndDate>

<cbc:EndTime>18:00:00</cbc:EndTime>

</cac:ValidityPeriod>

The seller may set the condition that the offer made in the shopping cart is only valid if all item in the cart are ordered.
That is the buyer may not select only certain items or change the quantities of the items listed in the cart.
This is given by the complete cart indicatior.
If the value of the indicator is "true" the buyer must either order all or none of the cart.
The default value of the indicator is "false" meaning that if the element is not included in the message the buyer may order part of the cart.
Following is an example.

<cbc:ActionCode>true</cbc:ActionCode>

The seller may reference a contract that governs the offer made in the shopping cart.
The terms and conditions of a referenced contract supersedes the information given in individual shopping carts.
Following is an example:

<cac:ReferencedContract>

<cbc:ID>CRT1387</cbc:ID>

</cac:ReferencedContract>
