= Attachments on header level

Non-XML documents can be sent as attachments to the PEPPOL BIS Order Agreement. This could be timesheets or other documents relevant for the order agreement. The attachment can either be sent as a binary object encoded in Base64 embedded in the message or as a URI to an external address as a link.

It is recommended to send attachments as embedded, binary objects and not as external references.

[cols=",",options="header",]
|====
|Element |Description
|Coding |Base64
|Document format a|
The following MIME types are recommended:
Pdf – application / pdf
TXT – text / plain
GIF – image / gif
Jpeg –image
PNG -image
Other MIME types may be used, subject to agreement.
|Size |Recommended maximum message size is 100MB including attachments.
|Description |It is recommended to use element cac:AdditionalDocumentReference/cbc:DocumentType to send a short description of the content of the attachment. +
NB: Attachments should be used for additional information and not as order copies.
|====

Example of attachment as an embedded, binary object in an PEPPOL BIS Order Agreement message.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=AdditionalDocumentReference]
----

= Attachments and document references on line level

Non-XML documents can be sent as attachments to the PEPPOL BIS Order Agreement on line level. This could comprise item specifications, timesheets or other documents relevant for the particluar line in the order agreement. See the above information regarding attachments.

Attachment as an embedded, binary object in an PEPPOL BIS Order Agreement message on line level.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=ItemSpecificationDocumentReference]
----

Link to a downloadable ticket.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=ItemSpecificationDocumentReference2]
----
