[[description-of-selected-parts-of-the-order-agreement-message]]
= Description of selected parts of the order agreement message

Following clauses describe the use of individual sections of the order agreement transaction.

== Parties

The following parties/roles may be specified in the message:

=== SellerSupplierParty (Seller)

The seller is the legal person or organization acting on behalf of the supplier and who sells goods or services to the buyer. The seller is mandatory in the PEPPOL BIS Order Agreement message.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=seller]
----

=== BuyerCustomerParty (Buyer)

The buyer is the legal person or organization acting on behalf of the customer and who buys or purchases the goods or services. The buyer is mandatory in the PEPPOL BIS Order Agreement message.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=buyer]
----

=== OriginatorCustomerParty (Originator)

The unit initiating the order. Most often the end user. The originator information is optional in the PEPPOL BIS Order Agreement message.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=originator]
----

=== AccountingCustomerParty (Invoicee)

The invoicee is the legal person or organization acting on behalf of the customer and who receives the invoice for the order. The invoicee information is optional in the PEPPOL BIS Order Agreement message.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=customer]
----

== Delivery

Delivery gives information on when and where the goods and services are deleivered.

Delivery special terms may be used to inform how the the goods or service is delivered. E.g.

* A ticket may be delivered as a pdf in mail - “Mail”.
* Goods may hav been collected at the store – “Customer pick up“

The delivery information is optional in the PEPPOL BIS Order Agreement message.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=delivery]
----

== References

When sending the order agreement transaction the seller may include a reference that the buyers gave to him during the purchase. This reference can be of different nature and since it originates from the buyer it is understood by him.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=CustomerReference]
----

The order agreement may refrence a previous order agreement. This may be relevant, as example, when the buyer has changed a previous order.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=OrderReference]
----

The order agreement may reference a contract that applies to the purchase.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=Contract]
----

== Attachments on header level

Non-XML documents can be sent as attachments to the PEPPOL BIS Order Agreement. This could be timesheets or other documents relevant for the order agreement. The attachment can either be sent as a binary object encoded in Base64 embedded in the message or as a URI to an external address as a link.

It is recommended to send attachments as embedded, binary objects and not as external references.

[cols=",",options="header",]
|====
|Element |Description
|Coding |Base64
|Document format a|
The following MIME types are recommended:

Pdf – application / pdf

TXT – text / plain

GIF – image / gif

Jpeg –image

PNG -image

Other MIME types may be used, subject to agreement.

|Size |Recommended maximum message size is 100MB including attachments.
|Description |It is recommended to use element cac:AdditionalDocumentReference/cbc:DocumentType to send a short description of the content of the attachment. +
NB: Attachments should be used for additional information and not as order copies.
|====

Example of attachment as an embedded, binary object in an PEPPOL BIS Order Agreement message.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=AdditionalDocumentReference]
----

== Attachments and document references on line level

Non-XML documents can be sent as attachments to the PEPPOL BIS Order Agreement on line level. This could comprise item specifications, timesheets or other documents relevant for the particluar line in the order agreement. See the above information regarding attachments.

Attachment as an embedded, binary object in an PEPPOL BIS Order Agreement message on line level.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=ItemSpecificationDocumentReference]
----

Link to a downloadable ticket.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=ItemSpecificationDocumentReference2]
----

== Product identification

Product identification may be done using the identifiers described below:

* Sellers ID
* Standard ID, e.g. the GS1 Global Trade Item Number (GTIN) [GS1]

The order agreement requires that an item has an identifier. This can be either the sellers idenfier or a standard identifier. Which identifier to use depends on what is known at the time of the purchase or what is commonly used in the relevant business sector.

Example of an PEPPOL BIS Order Agreement item using both Sellers ID and Standard ID (GTIN):

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=ItemIdentifiers]
----

== Product name and description

The Product name must be sent in tag Item/Name on line level. Description of a product can be sent in Item/Description.

The Product name is often sent in the order agreement from the buyer to the seller.

Example in an PEPPOL BIS Order Agreement message:

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=ItemDescription]
----

== Item labelling

Information about the items environmental, social, ethical and quality type of labelling. The UBL structure used for item labeling requires certain elements in addition to those used by this BIS. To fulfill the UBL requirements these are included with the dummy value NA.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=Certificate]
----

== Contracted item

If the purchased item is offered in accordance to an existing contract, this should be indicated in the order agreement message.

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=TransactionConditions]
----

== Quantities and units

Various Quantities and Units can be stated in the PEPPOL BIS Order Agreement. These are both related to the ordering process and the logistics process.

The table below lists quantities and units in the format. To all quantities there must be a valid Unit of measure according to the Code list.

[cols=",",options="header",]
|====
|Element name / (Tag name) |Description
|Price Quantity / +
(BaseQuantity) |Quantity related to Price.
|Order Quantity / +
(Quantity) |Quantity that is ordered, e.g. number of pieces or volume in litre .
|====

Example of an order agreement line with a quantity of 120 pieces (cbc:Quantity) and price is given per items. When calculating the line amount the price is applied pr 12 pieces, that is 120/12x50 = €500

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=quantity]
----

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=Price12]
----


    <cac:Price> +
<cbc:PriceAmount currencyID="EUR">50</cbc:PriceAmount>

<cbc:BaseQuantity unitCode="C62">12</cbc:BaseQuantity>

    </cac:Price>

== Prices

Prices must be exchanged in the Order Agreement transaction. The price may be 0 (zero)

Price sent is related to the articles or services within this order agreement

Prices includes allowances and/or charges but exclude VAT amounts

Example of price information in an Order Agreement message:

      …

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=price]
----


<cac:Price>

<cbc:PriceAmount currencyID="EUR">50</cbc:PriceAmount>

<cbc:BaseQuantity unitCode="C62">1</cbc:BaseQuantity>

</cac:Price>

== Allowances and charges

This example shows a charge related to packing costs:

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=AllowanceCharge]
----


<cac:AllowanceCharge>

<cbc:ChargeIndicator>false</cbc:ChargeIndicator>

<cbc:AllowanceChargeReason>Discount</cbc:AllowanceChargeReason>

<cbc:Amount currencyID="EUR">100</cbc:Amount>

</cac:AllowanceCharge>

This example shows an allowance related to a discount on the order:

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=AllowanceCharge2]
----


<cac:AllowanceCharge>

<cbc:ChargeIndicator>true</cbc:ChargeIndicator>

<cbc:AllowanceChargeReason>Packing cost</cbc:AllowanceChargeReason>

<cbc:Amount currencyID="EUR">200</cbc:Amount>

</cac:AllowanceCharge>

== Calculation of totals (LegalMonetaryTotal)

The following elements show the anticipated monetary totals for an order agreement:

[cols=",",options="header",]
|====
|Element: |Description:
|<cbc:LineExtensionAmount> |Sum of line amounts
|<cbc:AllowanceTotalAmount> |Allowances on document level
|<cbc:ChargeTotalAmount> |Charges on document level
|<cbc:TaxExclusiveAmount> |Order total amount without VAT
|<cbc:TaxInclusiveAmount> |Order total amount included VAT
|<cbc:PrepaidAmount> |Any amounts that have been paid a-priory
|<cbc:PayableRoundingAmount> |Rounding of Order total
|<cbc:PayableAmount> |The amount that is expected to be paid
|====

Amounts MUST be given to a precision of two decimals except for Price where maximum number of decimals are four.

Expected total payable amount MUST NOT be negative.

Expected total sum of line amounts MUST NOT be negative.

Note that the LegalMonetaryTotals class is optional. The legal monetary total class in the order agreement is equal to the anticipated monetary total in the order transaction. If the class is included in the message, the only mandatory elements are the LineExtensionAmount and the PayableAmount elements. All other elements are optional. When optional elements are used, the content MUST be according to the rules below.

Formulas for the calculations of totals are as follows:

[cols=",",options="header",]
|====
|Element: |Formula:
|<cbc:LineExtensionAmount> |∑ LineExtensionAmount (at line level)
|<cbc:ChargeTotalAmount> |∑ Charge Amount (where ChargeIndicator = ”true”)
|<cbc:AllowanceTotalAmount> |∑ Allowance Amount (where ChargeIndicator = ”false”)
|<cbc:TaxExclusiveAmount> a|
LineExtensionAmount

– AllowanceTotalAmount

+ ChargeTotalAmount

|<cbc:TaxInclusiveAmount> a|
TaxExclusiveAmount

+ TaxTotal /TaxAmount

+ PayableRoundingAmount

|<cbc:PayableAmount> |TaxInclusiveAmount – PrepaidAmount
|====

=== Example of calculations:

[cols=",,,",options="header",]
|====
|*Business term* | |*Sample amounts* |*Element*
|Sum of line amounts |+ |1436.50 |LineExtensionAmount
|Allowance on document level |- |100.00 |Allowances(Total)
|Charges on document level |+ |200.00 |Charges(Total)
|Total amount without VAT |= |1536.50 |TaxExclusiveAmount
|VAT total amount |+ |384.13 |TaxAmount
|Rounding of Order total |+ |0.37 |PayableRoundingAmount
|Total with VAT (value of purchase) |= |1921.00 |TaxInclusiveAmount
|Paid amounts |- |1000.00 |PrepaidAmount
|Amount expected to be paid |= |921.00 |Payable amount
|====

The above example is presented in the order agreement in the following way:

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=LegalMonetaryTotal]
----


<cac:LegalMonetaryTotal>

<cbc:LineExtensionAmount currencyID="EUR">1436.50</cbc:LineExtensionAmount>

<cbc:TaxExclusiveAmount currencyID="EUR">1536.50</cbc:TaxExclusiveAmount>

<cbc:TaxInclusiveAmount currencyID="EUR">1921</cbc:TaxInclusiveAmount>

<cbc:AllowanceTotalAmount currencyID="EUR">100</cbc:AllowanceTotalAmount>

<cbc:ChargeTotalAmount currencyID="EUR">200</cbc:ChargeTotalAmount>

<cbc:PrepaidAmount currencyID="EUR">1000</cbc:PrepaidAmount>

<cbc:PayableRoundingAmount currencyID="EUR">0.37</cbc:PayableRoundingAmount>

<cbc:PayableAmount currencyID="EUR">921.00</cbc:PayableAmount>

</cac:LegalMonetaryTotal>

=== Element for rounding amount, the PayableRoundingAmount

It is possible to round the expected payable amount. The rule for this is according to the standard rule regarding rounding, i.e. greater than or equal to 0.5 is rounded up, all other values are rounded down.

The element LegalMonetaryTotal/PayableRoundingAmount is used for this purpose and is specified on the header level. This value must be added to the value in LegalMonetaryTotal/TaxInclusiveAmount.

Example: Amount 999.81 rounded to 1000. PayableRounding Amount = 0.19

== Tax amounts

It is possible to state the tax total of the order agreement, on the header level and also on line level.

Header level:

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=TaxTotal]
----


<cac:TaxTotal>

<cbc:TaxAmount currencyID="EUR">1236</cbc:TaxAmount>

<cac:TaxSubtotal>

<cbc:TaxableAmount currencyID="EUR">1000</cbc:TaxableAmount>

<cbc:TaxAmount currencyID="EUR">236</cbc:TaxAmount>

<cac:TaxCategory>

<cbc:ID schemeID="UNCL5305">S</cbc:ID>

<cbc:Percent>23.6</cbc:Percent>

<cac:TaxScheme>

<cbc:ID schemeID="UNCL5153">VAT</cbc:ID>

</cac:TaxScheme>

</cac:TaxCategory>

</cac:TaxSubtotal>

</cac:TaxTotal>

Line level:

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=LineItem]
----


<cac:LineItem>

<cbc:ID>1</cbc:ID>

<cbc:Note>Line note</cbc:Note>

<cbc:Quantity unitCode="C62">12</cbc:Quantity>

<cbc:LineExtensionAmount currencyID="EUR">1000</cbc:LineExtensionAmount>

<cbc:TotalTaxAmount currencyID="EUR">236</cbc:TotalTaxAmount>

…

.Example
[source, xml, indent=0]
----
include::../snippets/OA full.xml[tags=ClassifiedTaxCategory]
----


<cac:ClassifiedTaxCategory>

<cbc:ID schemeID="UNCL5305">S</cbc:ID>

<cbc:Percent>23.6</cbc:Percent>

<cac:TaxScheme>

<cbc:ID schemeID="UNCL5153">VAT</cbc:ID>

</cac:TaxScheme>
