[[party-identifiers]]
= Party Identifiers

The “schemeID” attribute must be populated in all instances of the “ID” element when used within a “PartyIdentification”-container and in all instances of the “EndpointID” element when used within a “Party”-container.

Example of using GS1 GLN (Global Location Number) as PartyIdentification:

[source, xml, indent=0]
----
include::../snippets/snippet-1-2.xml[tags=partyid-gln]
----


[[using-danish-organization-number-as-partyidentification]]
== Using Danish organization number as PartyIdentification

In Denmark parties often are identified by a company organization number.
This can be used for all parties.

The following examples denotes that the Issuing Agency is DK:CVR in the PEPPOL set of Issuing Agency

Codes.
This means that the party has the Danish CVR identifier DK87654321.

Examples of usage in PartyIdentification and Endpoint ID:


[source, xml, indent=0]
----
include::../snippets/snippet-1-2.xml[tags=endpointid-dk]
----

[source, xml, indent=0]
----
include::../snippets/snippet-1-2.xml[tags=partyid-dk]
----


[[using-swedish-organization-number-as-partyidentification]]
== Using Swedish organization number as PartyIdentification

In Sweden parties often are identified by a company organization number.
This can be used for all parties.

[source, xml, indent=0]
----
include::../snippets/snippet-1-2.xml[tags=partyid-se]
----

[[using-italian-vat-number-as-partyidentification]]
== Using Italian VAT number as PartyIdentification

In Italy parties often are identified by the VAT number.
This can be used for all parties.

[source, xml, indent=0]
----
include::../snippets/snippet-1-2.xml[tags=partyid-it]
----
