[[technical-parameters]]
= Technical parameters

[[ubl-version-id]]
== UBL Version ID

This BIS is using the UBL 2.1 syntax.
The namespace of the XML-message does only communicate the major version number.
Since it is important for the receiver to also know what minor version of the syntax that is used, the element UBLVersionID must be stated with the value *2.1.*

[[profile-id]]
== Profile ID

The ProfileID identifies the process the business document is part of.
PEPPOL BIS uses the identification system according to BII:

**ProfileID**: urn:www.cenbii.eu:profile:bii30:ver2.0

[[customization-id]]
== Customization ID

The Customization identifies the specification of content and rules that apply to the transaction.
This BIS has required some minor additions and changes to the CEN BII transaction.
Following the CENBII methodology any extension must be communicated by adding an extension ID onto the Customization ID.

**Original CustomizationID**: urn:www.cenbii.eu:transaction:biitrns016:ver1.0

*OpenPEPPOL ExtensionID:* urn:www.peppol.eu:bis:peppol30a:ver1.0

*CustomizationID to use:*

urn:www.cenbii.eu:transaction:biitrns016:ver1.0:extended:urn:www.peppol.eu:bis:peppol30a:ver1.0

[[namespaces]]
== Namespaces

The target namespace for the UBL2.1 Despatch Advice is:

*urn:oasis:names:specification:ubl:schema:xsd:DespatchAdvice-2*
