[[process-requirements]]
= Process requirements

Process requirements describe what functions and benefits the parties are requiring from the overall process of exchanging Invoice Response messages.
These requirements may influence the data requirements in the transaction, but they may also affect how the parties implement and use the Invoice Response in their ongoing business exchange.

.Process requirements
[cols="1h,5",options="header"]
|====
|ID
|Requirement
|br111-001
|There is an agreed way to express when there will be no more Invoice Response's regarding a particular invoice.
The definition of status of the Invoice (whether approved or rejected) should clearly state whether it is a final status after which the receiver cannot send any further Invoice Responses in relation to that Invoice.

|br111-002
|An Invoice Response is intended for automatic processing on the issuer side although it still might require some manual actions.
Free text response is also an option inside the Invoice Response.
Validation rules might be automatically or manually executed on the receiver's side.
The receiver might outsource the rule's execution to a service provider.

|br111-003 |
An Invoice Response should clearly inform the issuer of any additional actions it should execute so that the receiver can continue the Invoice processing.

|br111-004
|An Invoice Response is an invoice-specific message based on the receiver's business rules and/or a Seller/Buyer agreement.

|br111-005
a|An Invoice Response is a one directional message from the receiver of the referenced business document to its issuer.

The direction is Buyer to Seller for standard billing and Seller to Buyer for self-billing. The response informs the issuer about the Invoice status inside the receiver's business process and any potential actions the issuer should take.

|br111-006
|An Invoice Response status code is unambiguous: when applicable, it must be used to clearly indicate the next expected action to be executed by the issuer (described in Table below).
|====

[[registering-the-invoice-response-receiving-capability]]
== Registering the Invoice Response receiving capability

In order to use the Invoice Response in the {peppol} network the following steps need to be carried out:

* The issuer shall register the capability to receive Invoice Response BIS63A in its SMP. This is the Seller in standard billing and the Buyer in self-billing.
* The issuer is seen as the interested party to find out if the document receiver is capable of sending an Invoice Response.
** Usually the exchange of Invoice Response is agreed by the business parties beforehand.

IMPORTANT: However, if the issuer has registered the receiving capability in the SMP, then the document receiver can send an Invoice Response without previous agreement.

* It is strongly recommended that a document receiver that sends an Invoice Response does so for all received Invoices.
Not doing so may create uncertainty for the issuer and therefore create unwanted processing for both the Buyer and Seller.
