[[code-policy]]
= Code Policy

Key information in an Invoice Response is the reporting of the status of the invoice.
The objective of the status code is to provide the issuer with a clear indication of the status of the referenced invoice inside the receiver's process in a way that allows the issuer to clearly identify if an action is required.
The status code can be supplemented with a clarification, an action code, or a textual note that explains the status and assists the issuer in deciding on the correct reaction.

The codes in the Invoice Response are given in the following structure.

====
* Invoice Status (1..1) 'cac:DocumentResponse/Response/cbc:ResponseCode'
** Clarification (0..n)
*** Data (0..n)
====

Each Invoice Response must have one and only one status code.

For each Invoice Response (status) there is the option of providing one or more clarification.

For each clarification there is the option to provide data that the receiver proposes as a correction.

.Example
====
An invoice may have been put under query (status UQ), as clarification the code XYZ is given to indicate that there is an issue with the references in the invoice.
As data the Invoice Response may state that the expected value for the Purchase Order reference in the invoice was PO123.
====

:leveloffset: +1

include::status-codes.adoc[]

include::clarification.adoc[]

:leveloffset: -1
