[[status-codes-1]]
= Status codes

.The following policies apply to the use of status codes:
* List of Status codes is fixed and can not be changed bilaterally.
* There are seven pre-agreed status codes (main statuses).
* The status code is sent from the receiver of the invoice to its issuer to inform the issuer about further processing of the invoice on the receiver's side.
* The status code does not inform the issuer of the business reason for the status (there is a clarification code for that).
* Every status can be the first status sent to the issuer, but further statuses must follow a defined order (see <<invoice-response-process-rules>>, rule OP-BR111-R012).
* Maximum time for first response is 3 days – The issuer should receive the first Invoice Response within 3 working days.
** By receiving the first response message, the issuer will know that an Invoice has been received and what its status is.
** If the issuer does not receive any response, it should wait 3 working days before contacting the receiver to query whether the Invoice was received.
** A receiver should therefore provide a first response before that time to notify the issuer that the Invoice has been received and what its status is.
* The minimum set of statuses that must be supported by a receiver is “Message acknowledged”, “Rejected” and “Approved”.


.The columns in the below table shall be understood as follows:
[horizontal]
Status code:: The code that defines the status of the reference document, e.g. AP.

UNECE name:: The name of the code, based on UNECE code list 4343.

UNECE definition:: The definition of the code, based on UNECE code list 4343.

BIS usage:: An explanation of how the UNECE definition of the code shall be interpreted and applied in transactions that follow this BIS.

Response expected::
Indicates that the document receiver expects a response from the issuer in accordance with the information given in the Invoice Response.
If no response is expected, then the receiver will proceed with the processing of the invoice without interruption.
If a response is expected, then the receiver will not proceed with the processing until the issuer has provided the response (externally).

Clarification required:: Indicates that when an Invoice Response contains this code, a clarification must be provided by the document receiver in the form of a Status Reason code (See {link-codelist}), text, or both.

Mandatory::
Indicates that a document receiver who supports this BIS shall at minimum be able to report these statuses in the processing of the invoice.
In other words, the issuer can at minimum expect to receive this status information.

Final::
Indicates that this is a final status in the processing of the referenced invoice.
The issuer will not receive any further Invoice Response messages referencing this invoice.

.The Status codes used in an Invoice Response are defined in the below table and are a subset UNECE code list 4343 with additional codes.
[cols="1h,1,3,3,1,1,1,1",options="header"]
|====
|Status Code
|UNECE name
|UNECE definition
|BIS usage
|Response expected
|Clarification Required
|Mandatory
|Final
|AB |Message acknowledgement |Indicates that an acknowledgement relating to receipt of message or transaction is required. |Status is used when the receiver has received a readable invoice message that can be understood and submitted for processing. |NO |NO |YES |NO
|IP |In Process |Indicates that the referenced message or transaction is being processed. |Status is used when processing of the Invoice has started in the receiver's system. |NO |NO |NO |NO
|UQ |Under query |Indicates that the processing of the referenced message has been halted pending response to a query. |Status is used when the receiver will not proceed to accept the Invoice without receiving additional information from the issuer. |YES |YES |NO |NO
|CA |Conditionally accepted |Indication that the referenced offer or transaction (e.g., cargo booking or quotation request) has been accepted under conditions indicated in this message. |Status is used when the receiver is accepting the Invoice under conditions stated in ‘Status Reason’ and will proceed accordingly unless disputed by the issuer. |NOfootnote:[When an invoice is conditionally accepted (CA), the receiver will proceed with processing according to the conditions it has stated.
The issuer may still respond externally if it has comments or objections to the conditions given.] |YES |NO |NO
|RE |Rejected |Indication that the referenced offer or transaction (e.g., cargo booking or quotation request) is not accepted. |Status is used only when the receiver will not process the referenced Invoice any further. +
The receiver is rejecting this invoice but not necessarily the commercial transaction.
Although it can be used also for rejection for commercial reasons (invoice not corresponding to delivery). |YES |YES |YES |YES
|AP |Accepted |Indication that the referenced offer or transaction (e.g., cargo booking or quotation request) has been accepted. |Status is used only when the receiver has given final approval of the invoice. |NO |NO |YES |NO
|PD with PPD (1) |Partially Paid |Indicates that the referenced document or transaction has been partially paid. |Status is used together with Clarification Reason code PPD, only when the sender is responsible for payment and has initiated payment without having paid the accepted amount in full. |NO |NO |NO |NO
|PD |Fully Paid |Indicates that the referenced document or transaction has been paid. |Status is used only when the sender is responsible for payment and has initiated payment of the invoice. |NO |NO |NO |YES

|====

(1) Status code PD (Paid) together with Clarification Reason code PPD (Partially Paid) is the case when an invoice is partially paid with the intention of later paying the full invoice amount as was accepted.

The sequence of the status codes is fixed to allow the issuer, as receiver of the Invoice Response, to advance the status of the invoice in its systems in an orderly way. See <<invoice-response-process-rules>>.
This requires the document receiver to be conservative in reporting status and only advance an invoice when the status is reasonably certain.

The status of an invoice must advance in the following sequence, but any status may be the first one used or may be omitted.

1.  AB – Message acknowledgement
2.  IP – In process
3.  UQ – Under query (may be repeated before moving forward)
4.  CA – Conditionally accepted
5.  RE – Rejected
6.  AP – Accepted
7.  PD – Paid, can be in steps, partially paid and then paid.

.Examples of status advancement:
====
1.  In standard billing, if an invoice is paid right after being received, the Buyer can report with a single Invoice Response using the code PD.
2.  If an invoice has been put under query, then following the response from the issuer, the receiver may advance it to any of the following codes:
[horizontal]
 CA:: conditionally accepted
 RE:: Rejected
 AP:: Accepted
 PD:: Paid
====

Deviations from this sequence must be handled manually between the trading parties.
For example, if a receiver has stated that an invoice has been accepted, it can not later send an Invoice Response indicating that it is under query or rejected.
This does not prohibit the receiver from changing its decision, but it must report that to the issuer by other means than by using an Invoice Response.

The fixed order simplifies the automation of the processing for the receiver of the Invoice Response.
