

[[use-case-2b-invoice-is-in-process-but-postponed]]
= Use case 2b — Invoice is in process but postponed

[cols="1h,5",options="header",]
|====
|Use Case number |2b
|Use Case Name |Invoice is in process but postponed
|Assumption and description a|
Buyer informs Seller that a reference could not be validated but also indicates that a further attempt will be made to process the Invoice and so no further action is required at this time.

Buyer validates the invoice, but a Reference Number could not be matched to those on their system. +
 +
Buyer can re-attempt validation of the invoice (e.g. to allow updating of their internal Reference Number database in case the Reference Number details have not yet been processed ready for matching – or where the invoice arrives ahead of the goods).

|The flow |Invoice Response with 'In Process' status and clarification text when invoice processing will continue, as no valid Reference Number was found.
|Parties involved |Buyer +
Seller
|Result |Seller knows that the invoice is in the queue and the process is stopped until appointed date and then a further attempt will be made to match the Invoice.
|XML example |T111-uc002b-In process but postponed.xml #Add link#
|====
