= Version 3.0.15
[horizontal]
Release date:: May 2025

== BIS documentation

* BIS Ordering and Order Only
** RELEASE NOTES

== Changes to syntax
* Order transaction (T01) [MINOR CHANGE TO TRANSACTION VERSION NUMBER]
** Added new codelist to Item CertificateTypeCode (PackagingMarkedLabelAccrediationCode from GS1 GDSN) which can be used in addition to the current NA value. The element was previously fixed to NA as the element was mandatory in UBL.
* Order Change(T114)
** RELEASE NOTES
* Order Agreement(T110) 
** RELEASE NOTES
* Order Response transaction (T76)
** RELEASE NOTES
* Order Response transaction Advanced (T116)
** RELEASE NOTES
* Despatch Advice (T16) [MINOR CHANGE TO TRANSACTION VERSION NUMBER]
** New code values for net weight and net volume used for Despatch Advice (T16) line level measurement dimensions. Description of the elements updated accordingly (cbc:AttributeID and cbc:Measure).
* Catalogue transaction (T19)
** RELEASE NOTES
* Punchout transaction (T77)
** RELEASE NOTES

== Changes to code lists and validation artefacts
* New codelist for PackagingMarkedLabelAccrediationCode from GS1 GDSN
* Codelist 66313 (measurement dimensions) updated. Used in Despatch Advice (T16).

== Other
