= Version 3.0.10
[horizontal]
Release date:: 2022-11-03

== New BIS documents
* Added new document  - BIS Advanced Ordering 3.0 with the following transactions:
** New transaction - Peppol Order Change transaction 3.0 (T114)
** New transaction - Peppol Order Cancellation transaction 3.0 (T115)
** New transaction - Peppol Order Response Advanced transaction 3.0 (T116)
** Existing transaction - Peppol Order transaction 3.3 (T01)

== New transactions
* Peppol Order Change transaction 3.0 (T114)
* Peppol Order Cancellation transaction 3.0 (T115)
* Peppol Order Response Advanced transaction 3.0 (T116)

== BIS documentation
* Invoice Response
** Definition of status codes in section Status Codes corrected to be in line with rule OP-BR111-R012 so that Accepted is not a final status and Paid is a final status.
** Correction of examples in chapter 6.3  
* Editorial change in the documentaion templates. Many pages in previous releases had a "Last updated" timestamp in the page footer. The timestamp indicated when the HTML-page was generated by the documentation tool, not when the actual content of the page was updated/changed. The timestamp is now removed since it caused a lot of confusion. 
* Order Response example in the BIS documentation (sectino 7.1.1) has been corrected. The example shows a response with type "Received" (code AB) but the example said that there was amendments in the details (which is not allowed with code AB)  
* Catalogue with response
** Removed broken link to example files in section 6.8 and pointed out the main page Appendix A instead.
* Catalogue without response
** Removed broken link to example files in section 6.8 and pointed out the main page Appendix A instead.
* Correction of a bullet point explaining the example in section "Line TAX Category" in all BISes that uses it. 

== Changes to syntax
* Despatch Advice transaction (T16) 
** Reference to Sales Order Line number is added as an optional business term on Despatch advice line.
** Commodity Classification code added as an optional business term on Despatch advice line.
** Optional additional Document reference (incl business terms for attachments) added on header level. Optional business terms for Document references (no attachments) also added on line level.
** Optional business term for Carrier Party Identification added to the Carrier Party information.
** Optional TransportModeCode added on header level with codes from UN/ECE Rec 19.
** Cardinality of DeliveredQuantity on Despatch line changed to mandatory in syntax to correctly reflect the intention of the BIS. 
** Examples updated
* Order transaction (T01)
** New business terms for RequestedDeliveryPeriod, Start time (tir01-p042) and End time (tir01-p043). Example updated.
** New business term for Project reference/ID (tir01-p044). Example updated.
* Order Response transaction (T76)
** New business terms for PromisedDeliveryPeriod, Start time (tir76-p010) and End time (tir76-p011). Added to example.
* Order Agreement transaction (T110)
** Optional element DocumentTypeCode (tir110-p008) added on ItemSpecificationDocumentReference level. Example updated.
** Optional element CompanyID added for PartyLegalEntity in both Buyer (tir110-p009) and Seller (tir110-p010). Example updated.

== Changes to code lists and validation artefacts

* Validation of code values for Tax Category codes are removed to allow for non-EU categories. In previous release (3.0.4), the TaxScheme/ID was generalized to allow for other schemes than VAT but also that category code should have been generalized. This release addresses this shortcoming (with a consequence that category code isn't validated). The change affects the following transactions:
** Order transaction (T01)
** Order Response transaction (T76)
** Catalogue transaction (T19)
** Order Agreement transaction (T110)
** Punch Out transaction (T77)
* Added DocumentType codes for Order transactions (T01) to allow for blanket orders (code 221) and Call-off (code 226). Applies in BIS specifications Order Only and Ordering.
* Rule PEPPOL-COMMON-R049 (ICD 0007 - Swedish organization number) changed from severity warning to fatal (as announced in the may 2022 release)
* Correction in Rule PEPPOL-COMMON-R050 (validation of Australian Business Number (ABN)) corrected
* Added eas codes 9959. Removed 9906 and 9907.
* Added icd codes 0217, 0218, 0219, 0220
* Added Action code (UNCL1229) for Order Change
