= Version 3.0.13
[horizontal]
Release date:: May 2024

== BIS documentation

* BIS Catalogue
** Clarified the use of item identifiers. Previusly unclear in the description if "either one of" or "at least one of" Sellers Identifier or Standard Identifier must be stated. It is now clear that it is "at least one of". This change is in line with existing validation rules of the existence of the identifiers.
** Statement that Manufacturers item identifier must be stated if it exists is deleted since it was unclear how to interpret the statement and to impossible to verify.
** Updated use case 5 to describe the use of deposits using RequiredRelatedItem 

== Changes to syntax
* Order transaction (T01)

* Order Response transaction (T76)

* Catalogue transaction (T19)
** Added possibility (by use of a code) to indicate if an item is non-returnable after purchase. The element cac:TransactionConditions/cbc:ActionCode on item-level is used and the code is added to the codelist "Transaction condition code (OpenPeppol)", together with the previous code to indicate if an item is contracted (CT). The element cbc:ActionCode was previously fixed to the value 'CT' since it was the only allowed code, but with this change, it can be used for both purposes.
** Time may be given with time zone information.

== Changes to code lists and validation artefacts

* Update of PEPPOL-COMMON-R049 which validates identifiers using ICD/EAS 0007. The change is adding validation of the check number of a Swedish Organization number.

* Added rule to check that an OrderResponse with ResponseTypeCode CA (accepted with amendment on line level) actually has order response lines. The rule is introduced with severity warning and will be changed to severity fatal in next release. The rule is added to both T76 (Order Responseand) and T116 (Order Response Advanced).

== Other
