= Version 3.0.14
[horizontal]
Release date:: November 2024

== BIS documentation

* BIS Catalogue
** Added sample file and use case which describes consignment orders and vendor-managed inventory for Order Only and Ordering BIS.

* BIS Ordering and Order Only
** Added sample file and use case which describes consignment orders and vendor-managed inventory

== Changes to syntax
* Order transaction (T01)
* Order Response transaction (T76)
* Order Response transaction Advanced (T116)
* Despatch Advice (T16)
** Optional attribute added to indicate the scheme of the Transport Handling Unit identifier. 
** Optional party Delivery Party added to align with Order.

* Catalogue transaction (T19)
* Punchout transaction (T77)
    Add ”cac:DocumentReference” to Certificate.
    this may contain vital information regarding the label and has a simular function as in Catalogue.

== Changes to code lists and validation artefacts
* Added new codelist with code values SSCC (Serial Shipping Container Code) and ZZZ (Mutually defined) to the optional attribute that indicates the type/scheme for Transport handling unit identifier (in Despatch Advice)

== Other
