= Version 3.0.10
[horizontal]
Release date:: 2022-11-

== BIS documentation
* Invoice Response
** Definition of status codes in section Status Codes corrected to be in line with rule OP-BR111-R012 so that Accepted is not a final status and Paid is a final status.

== Changes to syntax
* Despatch Advice transaction (T16) 
** Reference to Sales Order Line number is added as an optional business term on Despatch advice line.
** Commodity Classification code added as an optional business term on Despatch advice line.
** Optional additional Document reference (incl business terms for attachments) added on header level. Optional business terms for Document references (no attachments) also added on line level.
** Optional business term for Carrier Party Identification added to the Carrier Party information.
** Optional TransportModeCode added on header level with codes from UN/ECE Rec 19.
** Cardinality of DeliveredQuantity on Despatch line changed to mandatory in syntax to correctly reflect the intention of the BIS. 
** Examples updated
* Order transaction (T01)
** New business terms for RequestedDeliveryPeriod, Start time (tir01-p042) and End time (tir01-p043). Example updated.
** New business term for Project reference/ID (tir01-p044). Example updated.
* Order Response transaction (T76)
** New business terms for PromisedDeliveryPeriod, Start time (tir76-p010) and End time (tir76-p011). Added to example.
* Order Agreement transaction (T110)
** Optional DocumentTypeCode(tir110-p008) added on ItemSpecificationDocumentReference level. Example updated.

== Changes to code lists and validation artefacts

* Validation of code values for Tax Category codes are removed to allow for non-EU categories. In previous release (3.0.4), the TaxScheme/ID was generalized to allow for other schemes than VAT but also that category code should have been generalized. This release addresses this shortcoming (with a consequence that category code isn't validated). The change affects the following transactions:
** Order transaction (T01)
** Order Response transaction (T76)
** Catalogue transaction (T19)
** Order Agreement transaction (T110)
** Punch Out transaction (T77)
* Added DocumentType codes for Order transactions (T01) to allow for blanket orders (code 221) and Call-off (code 226). Applies in BIS specifications Order Only and Ordering.