= Version 3.0.15
[horizontal]
Release date:: May 2025
* Date of member review: 2024-03-07
* Date of publication: 2025-05-19
* Mandatory to use from: 2025-08-21

== BIS documentation

//* BIS Ordering and Order Only
//** RELEASE NOTES

== Changes to syntax
* Order transaction (T01)
** Added business terms and elements for the requested despatch date and time (The date/time on which the buyer requests the ordered goods be ready for pickup at the seller’s warehouse or an agreed-upon pickup location.)
** Added Physical delivery location on order line level
** Patched schematron version to 3.6
//* Order Change(T114)
//** RELEASE NOTES
//* Order Agreement(T110) 
//** RELEASE NOTES 
* Order Response transaction (T76)
** Rule PEPPOL-T76-R007 that checks that order responses with code CA (conditional changes) has lines, is changed from warning to fatal in line with previous release notes.
* Order Response transaction Advanced (T116) 
** Rule PEPPOL-T116-R007 that checks that order responses with code CA (conditional changes) has lines, is changed from warning to fatal in line with previous release notes.
* Catalogue transaction (T19)
** Added new codelist to Item CertificateTypeCode (PackagingMarkedLabelAccrediationCode from GS1 GDSN) which can be used in addition to the current NA value. The element was previously fixed to NA as the element was mandatory in UBL.
** Changed example values on cac:ProviderParty/cbc:EndpointID, cac:ReceiverParty/cbc:EndpointID,
cac:SellerSupplierParty/cbc:EndpointID and cac:ContractorCustomerParty/EndpointID
* Despatch Advice (T16) 
** New code values for net weight and net volume used for Despatch Advice (T16) line level measurement dimensions. Description of the elements updated accordingly (cbc:AttributeID and cbc:Measure).
** Added ProductTraceID to Despatch Advise for the implementation of UDI (Unique Device Identifier) information for Medical Devices
//* Punchout transaction (T77)
//** RELEASE NOTES

== Changes to code lists and validation artefacts
* New codelist for PackagingMarkedLabelAccrediationCode from GS1 GDSN
* Codelist 66313 (measurement dimensions) updated. Used in Despatch Advice (T16).
* New codelist for ProductTraceID
* Changes to codelists
[cols="1,1,1"]
|===
|codelist|removed|added

|eas |7 [0037,0177,0202,0212,0213,0215,9901] |3 [0205,0225,0240]
|icd |0 [] |2 [0239,0240]
|ISO4217 |2 [CUC,ZWL] |1 [XXX]]
|UNCL5305 |1 [B] |0 []
|UNCL7143 |0 [] |1 [PPI]
|===

== Other
