= Version 3.0.9
[horizontal]
Release date:: 2022-05-30

== Changes to code lists and validation artefacts

* Added rule to check format for Swedish organisation numbers (ICD/EAS 0007) with severity warning, will be changed to fatal in future release.

* An error has been corrected which is causing some XSL-transformers/tools to raise errors when loading/using the schematron-files.

* Rule PEPPOL-COMMON-R043 (ICD 0208) changed from severity warning to fatal (as announced in the november 2021 release)

* Correction in Punch Out rule PEPPOL-T77-R001 that was incorrectly fired when validity period is omitted

* Added rule to check format for Australian ABN  (ICD/EAS 0151) with severity warning, will be changed to fatal in future release.

* Added test file for Catalogue wo response Use case 5

* Added codes 0214, 0215 and 0216 to the ICD code list and support added in validation artefacts. [505]

* Added codes 0147, 0170, 0188, 0215 and 0216 to the EAS code list and support added in validation artefacts. [481,473,505,506]

* Double entry of code TSP removed from code list UNCL7143. [488]
