= Version 3.0.5 - 2020 Fall
[horizontal]
Release date:: 2020-11-01

== Changes to BIS document
* Corrected use of charge indicatior false vs true in table in section 6.9 in order transaction. Issue: [POACC-352]
* BIS "Catalogue only" renamed to "Catalogue with response". Issue: [POACC-357]
* Added new business term to PunchOut for External attachment reference as tir77-p003 to align with text in BIS [POACC-354]
* Migration plan from BIS2 to BIS3 removed. Is completed.

== Changes to syntax
* For the Catalogue (T19) cbc:PriceType/cac:ValidityPeriod (tir19-056/057) is marked as unbounded in the syntax description while the validation rules and BIS description expects maximum 1. Cardinality changed to 0..1 to align with requirements and business rules. [POACC-340]

== Changes to supporting documents


== Changes to code lists and validation artefacts
* Rule PEPPOL-COMMON-R040: "GLN must have a valid format according to GS1 rules". Changed from severity "warning" to "fatal". (The rule was introduced in fall 2019 with severity "warning" to avoid disruptions but with the intention to be changed to severity "fatal" after 6-12 months). Issue: [POACC-333] and [POACC-341]
* EAS code list, added code 0209, removed code 9958. Peppol rule updated accordingly.
* ICD code list, added code 0205, 0206, 0207, 0208, 0209. 
* Duplicate currency codes removed from ISO4217 code list. Issue: [POACC-339]
* OrderAgreement - Rule T110-R027 (verifies structure of tax categories) changed so that the rule is triggered only when it should be. [POACC-330]
