= Version 3.0.17
[horizontal]
Release date:: May 2026
* Date of member review: 2026-MM-DD
* Date of publication: 2026-MM-DD
* Mandatory to use from: 2026-MM-DD

== BIS documentation

* Invoice Response BIS
** New profile added for a process where the invoice response is a required step in the collaboration. The profile requires a separate SMP registration. The same profile identifier has been added to BIS Billing 3.0.

== Changes to syntax
* Order transaction (T01) [MINOR]
** Added business term for providing reference to quotation line from order line. Rule added that the quotation line reference is only allowed when the quotation document reference is also provided.
   https://openpeppol.atlassian.net/browse/RFC-530

* Order Change(T114) [MINOR]
** Added business term for providing reference to quotation line from order line. Rule added that the quotation line reference is only allowed when the quotation document reference is also provided.
   https://openpeppol.atlassian.net/browse/RFC-530
   
* Order Response Advanced transaction (T116) [EDITORIAL]
** Bugfix: Correction of example value for CustomizationID
https://openpeppol.atlassian.net/browse/PEPPOL-17392
 
* All transactions [Editorial]
** Examples added when missing for all business terms

== Changes to code lists and validation artefacts

==  EN 16931 schematrons updated
