= Version 3.0.10
[horizontal]
Release date:: 2022-11-

== Changes to syntax
* Despatch Advice transaction (T16) - Reference to Sales Order Line number is added as an optional business term on Despatch advice line.
* Despatch Advice transaction (T16) - CommodityClassification code added as an optional business term on Despatch advice line.

== Changes to code lists and validation artefacts

* Validation of code values for Tax Category codes are removed to allow for non-EU categories. In previous release (3.0.4), the TaxScheme/ID was generalized to allow for other schemes than VAT but also that category code should have been generalized. This release addresses this shortcoming (with a consequence that category code isn't validated). The change affects the following transactions:
** Order transaction (T01)
** Order Response transaction (T76)
** Catalogue transaction (T19)
** Order Agreement transaction (T110)
** Punch Out transaction (T77)
* Added DocumentType codes for Order transactions (T01) to allow for blanket orders (code 221) and Call-off (code 226). Applies in BIS specifications Order Only and Ordering.