= Version 3.0.16
[horizontal]
Release date:: November 2025
* Date of member review: 2025-09-15
* Date of publication: 2025-11-24
* Mandatory to use from: 2026-02-23

== BIS documentation

* BIS Catalogue with and without response.
** Added extra use case and sample file which shows how dietary claims and product features can be expressed using code values [EDITORIAL CHANGE]
   https://openpeppol.atlassian.net/browse/RFC-456

* Invoice Response T111
** removed all references to IMR or IRM and the unnecessary word message. 
   https://openpeppol.atlassian.net/browse/RFC-480

* Corrected documentation references to use-case IDs to be used as anchors.

== Changes to syntax
* Order transaction (T01)
** Added business terms and elements for the delivery address on line level. Previously, only an identifier for the line level delivery address existed and with this change a full physical address and location name are possible to provide. [MINOR CHANGE]
   https://openpeppol.atlassian.net/browse/RFC-466

* Catalogue transaction (T19)
** Added attribute listVersionID on the AdditionalItemProperty NameCode element. [MINOR CHANGE]
   https://openpeppol.atlassian.net/browse/RFC-456

//* Order Change(T114)
//** RELEASE NOTES
//* Order Agreement(T110) 
//** RELEASE NOTES 
// * Order Response transaction (T76)
//** RELEASE NOTES 
//* Order Response transaction Advanced (T116) 
//* Catalogue transaction (T19)
* Despatch Advice (T16) 
** Added business terms and elements for additional item properties on ItemInstance. [MINOR CHANGE]
   https://openpeppol.atlassian.net/browse/RFC-457
//* Punchout transaction (T77)
//** RELEASE NOTES

== Changes to code lists and validation artefacts
//** RELEASE NOTES

* Changes to codelists
[cols="1,1,1"]
|===
|codelist|removed|added

//dummy values below, just to keep the table structure intact from last release. 
//|eas |1 [9901] |10 [0147,0154,0158,0170,0194,0203,0205,0217,0225,0240]
//|icd |0 [] |2 [0239,0240]
//|ISO4217 |2 [CUC,ZWL] |1 [XXX]]
//|UNCL7143 |0 [] |1 [PPI]
|===

==  EN 16931 schematrons updated

* Common rule R042 updated the test to: (string-length(string()) = 10) and (substring(string(), 1, 2) = 'DK') and (string-length(translate(substring(string(), 3, 8), '1234567890', '')) = 0)
  ** uses stricter test to only allow with DK prefix
  ** https://openpeppol.atlassian.net/browse/RFC-491

* NEW common rule R052 added to check for valid Danish chamber of commerce number (P) using test: (string-length(string()) = 8) and (string-length(translate(string(), '1234567890', '')) = 0)
  ** https://openpeppol.atlassian.net/browse/RFC-491

* Common rule R048 commented out, not used anymore

* Updated companion test files

* Resolved the issue "A function that computes atomic values should use xsl:sequence rather than xsl:value-of"

== Other
