= Version 3.0.7
[horizontal]
Release date:: 2021-05-03

== Changes to BIS document
* The version numbers used in the BIS-documentation were inconsistant with the actual version numbers listed on the main documentation page. Version numbers should now be aligned. [POACC-391]

*Changes in the documentation of Despatch Advice transaction 3.1. rule T16-R009 and T16-R010 is now reffering to seller party and originator customer party instead of buyer party [POACC-377].

*Clarification on the syntax documentation of Buyer reference identifier (ReceiverParty/Contact/ID) in Punch Out transaction 3.1 [POACC-363].

*Peppol logo updated to new design [POACC-375]

*In Order Agreement BIS. Duplicated headings and intro text 3.3 and 3.3.1 removed. Later sections renumbered accordingly. [POACC-393]

*Description of calculation of totals in Order Only BIS corrected so that class is shown as cac:AnticipatedMonetaryTotal instead of cac:LegalMonetaryTotal. No affect on functionality. [POACC-397]


== Changes to syntax
* An element which is mandatory in UBL was missing in the syntax description for the Order Transaction. The element (cac:Shipment/cbc:ID) is now added and with a fixed value "NA". A validation rule is also included which verifies that that the charactar NA are used when providing the element. The change was considered a bug-fix as the previous documentation would result in invalid UBL instances. [POACC-389 and POACC-380]

* The XML Elements for DeliveryParty Contact was incorrectly located under the DeliveryParty. The Contact element has been located correctly according to the UBL-schema.  The change was considered a bug-fix as the previous documentation would result in invalid UBL instances. [POACC-379]

* An editorial change has been made in the description of the element Order/CustomerReference in the Order Transaction. Previous wording "Your reference" is changed to "Buyer reference" aligning the description with the business term used in the Invoice. [POACC-364]

== Changes to code lists and validation artefacts

*ICD code list details edited to remove contact information [POACC-388]

*ICD code list. Added 0210, 0211, 0212, 0213 [POACC-407]

*EAS code list. Added 0210, 0211, 0212, 0213. Removed 9956 [POACC-407]

== Changes to previous release notes
* The date for the hotfix published in november 2020 was incorrectly dated to 2019. This date is corrected in this release.