= Version 3.0.14
[horizontal]
Release date:: November 2024

== BIS documentation

* BIS Ordering and Order Only
** Added sample file and use case which describes consignment orders and vendor-managed inventory

== Changes to "BIS compliance" document
* Added new compliance rules on how to use sender/receiver identifiers when enveloping a BIS3 message in Peppol Business Message Envelope (SBDH) nd its "schemeID" attribute

== Changes to syntax
* Order transaction (T01)
** Added optional element ID to AdditionalItemProperty with corresponding update in Use Case 4.
* Order Change(T114)
** Added optional element ID to AdditionalItemProperty.
* Order Agreement(T110) 
** Added optional element ID to AdditionalItemProperty with corresponding update in Use Case in Appendix A.
* Order Response transaction (T76)
** No changes
* Order Response transaction Advanced (T116)
** No changes
* Despatch Advice (T16)
** Optional attribute added to indicate the scheme of the Transport Handling Unit identifier.
** Optional Delivery Party added to align with Order.
** Added optional element ID to AdditionalItemProperty.
* Catalogue transaction (T19)
** Added optional element ID to AdditionalItemProperty with corresponding update in Use Case 5.
* Punchout transaction (T77)
** Added optional element ID to AdditionalItemProperty with corresponding update in Use Case in Appendix A.
** Added ”cac:DocumentReference” to Certificate.
*** this may contain vital information regarding the label and has a similar function as in Catalogue.

== Changes to code lists and validation artefacts
* Added new codelist with code values SSCC (Serial Shipping Container Code) and ZZZ (Mutually defined) to the optional attribute that indicates the type/scheme for Transport handling unit identifier (in Despatch Advice)

== Other
