= Version 3.0.14
[horizontal]
Release date:: November 2024

== BIS documentation

* BIS Ordering and Order Only
** Added sample file and use case which describes consignment orders and vendor-managed inventory

== Changes to Compliance BIS document
* Added new compliance on SBDH and BIS3 payload
** The value of the SBDH element "Sender/Identifier" MUST be equivalent to the value in the sender party’s "Party/EndpointID" element and its "schemeID" attribute.
** The value of the SBDH element "Receiver/Identifier" MUST be equivalent to the value in the receiver’s party "Party/EndpointID" element and its "schemeID" attribute

== Changes to syntax
* Order transaction (T01)
** Added optional element ID to AdditionalItemProperty with corresponding update in Use Case 4.
* Order Change(T114)
** Added optional element ID to AdditionalItemProperty.
* Order Agreement(T110) 
** Added optional element ID to AdditionalItemProperty with corresponding update in Use Case in Appendix A.
* Order Response transaction (T76)
** No changes
* Order Response transaction Advanced (T116)
** No changes
* Despatch Advice (T16)
** Optional attribute added to indicate the scheme of the Transport Handling Unit identifier.
** Optional Delivery Party added to align with Order.
** Added optional element ID to AdditionalItemProperty.
* Catalogue transaction (T19)
** Added optional element ID to AdditionalItemProperty with corresponding update in Use Case 5.
* Punchout transaction (T77)
** Added optional element ID to AdditionalItemProperty with corresponding update in Use Case in Appendix A.
** Added ”cac:DocumentReference” to Certificate.
*** this may contain vital information regarding the label and has a similar function as in Catalogue.

== Changes to code lists and validation artefacts
* Added new codelist with code values SSCC (Serial Shipping Container Code) to the optional attribute that indicates the type/scheme for Transport handling unit identifier (in Despatch Advice)

== Other
