[[codelists-for-coded-elements]]
= Codelists for coded elements

Table of the code lists used in the Despatch Advice transaction:

[cols="15%,15%,15%,25%,30%",options="header",]
|====
|*Business Term* |*Source* |*Subset* |*Xpath* |*listID*
|Country Code |ISO 3166-1 alpha2 |- |cac:Country/cbc:IdentificationCode |ISO3166-1:Alpha2
|Unit Of Measure |UN/ECE Rec 20 |- |@unitCode a|
UNECERec20

Note: Use this list identifier in the attribute unitCodeListID

|UNDG Code |UN CL 8273 |- |cbc:UNDGCode |UNCL8273
|Transport Handling Unit Type Code |UN/ECE Rec 21 |- |cbc:TransportHandlingUnitTypeCode |UNECERec21
a|
Handling unit gross weight and
Handling unit gross volume

 |UN CL 6313 a|
"AAB" for Unit gross weight

"AAW" for Gross volume

 |cac:MeasurementDimension/ +
cbc:AttributeID |UNCL6313 (use attribute schemeID)
|====

*ISO 3166-1 alpha2:*

http://www.iso.org/iso/home/standards/country_codes.htm

*UN/ECE Rec 20:*

http://www.unece.org/tradewelcome/areas-of-work/un-centre-for-trade-facilitation-and-e-business-uncefact/outputs/cefactrecommendationsrec-index/list-of-trade-facilitation-recommendations-n-16-to-20.html

*UN CL 8273*

http://www.unece.org/trade/untdid/d12b/tred/tred8273.htm

*UN CL 6313*

http://www.unece.org/trade/untdid/d12b/tred/tred6313.htm

*UN/ECE Rec 21*

http://www.unece.org/tradewelcome/areas-of-work/un-centre-for-trade-facilitation-and-e-business-uncefact/outputs/cefactrecommendationsrec-index/list-of-trade-facilitation-recommendations-n-21-to-24.html

[[codelists-for-identifier-schemes]]
= Codelists for identifier schemes

The table of the code lists below describes constrains for the values of schemeID for identifiers in the Despatch Advice transaction.

*Use of attributes for identifiers:*

[red]#schemeID# indicates what type of identifier is used (for example the type of numbering system) *(Mandatory)*

[red]#schemeAgencyID# indicates the agency responsible for issuing the ID (for example AgencyID 9 corresponding to GS1) *(Optional)*

[red]#schemeAgencyName# the name of the Agency responsible for issuing the ID. *(Optional)*

[cols=",,,",options="header",]
|====
|*Business Term* |*Allowed SchemeID* |*Applicable Xpath* |*Note*
|Party Identifier |See “PEPPOL Policy for using Identifiers” a|
cbc:EndpointID/@schemeID

cac:PartyIdentification/cbc:ID/@schemeID
 |
|====
