[[sending-and-receiving-parties]]
= Sending and receiving parties

As a response to an Invoice the Invoice Response is transmitted in the opposite direction, from the Buyer to the Seller or their respective service providers. The Invoice Response supports information about two pairs of parties. Those that are exchanging the Invoice Response and those who exchanged the invoice that is being responded to.

* SenderParty and ReceiverParty are the parties that are exchanging the Invoice Response message. These are the Buyer and the Seller unless they are using service providers to handle their invoices, in which case there are those service providers.
* IssuerParty and RecipientParty are the Seller and the Buyer as identifed on the invoice and can be identified in the Invoice Response if they are not themselves the SenderParty and/or ReceiverParty.

[[senderparty]]
== SenderParty

The party that sends the Invoice Response.
This is the Buyer who received the invoice, or it may be a service provider who is processing the invoice on behalf of the Buyer.
If the Invoice Response is issued by a service provider the name of the actual Buyer may be given as RecipientParty.

The information given for the sender is his EndpointID which is his PEPPOL Participant Identifier (PPID). The party identifier may be given as well and the schema that the identifier is based on.
The name of the sender is then provided.

Contact information for the sender is the person that the receiver of the Invoice Response can contact when resolving an issue reported in the response. This should not be a general company email and phone unless the sender has in place a process that would direct the contact efficiently to a relevant person.

.UBL example:
[source, xml]
----
<cac:SenderParty>
  <cbc:EndpointID schemeID="0196">6963495890</cbc:EndpointID>
  <cac:PartyIdentification>
    <cbc:ID schemeID="0088">senderif12345</cbc:ID>
  </cac:PartyIdentification>
  <cac:PartyName>
    <cbc:Name>Buyer organization</cbc:Name>
  </cac:PartyName>
  <cac:Contact>
    <cbc:Name>Invoice processing department</cbc:Name>
    <cbc:Telephone>012312312345</cbc:Telephone>
    <cbc:ElectronicMail>invoiceprocessingdepartment@organization.org</cbc:ElectronicMail>
  </cac:Contact>
</cac:SenderParty>
----

[[receiverparty]]
== ReceiverParty

The party who receives the Invoice Response. 
This is the Seller who issued the invoice, or a service provider who handles the invocing process on behalf of the Seller.
If the Invoice Response is sent to a service provider, then the actual Seller may be as IssuerParty.

.UBL example:
[source, xml]
----
<cac:ReceiverParty>
  <cbc:EndpointID schemeID="0196">6841569459</cbc:EndpointID>
  <cac:PartyIdentification>
    <cbc:ID schemeID="0088">receiver12345</cbc:ID>
  </cac:PartyIdentification>
  <cac:PartyName>
    <cbc:Name>Seller company</cbc:Name>
  </cac:PartyName>
</cac:ReceiverParty>
----

[[issuer-and-recipient-parties]]
== Issuer and Recipient parties

In the case when the Invoice processing is handled by a service provider on behalf of the Buyer and/or the Seller then the Sending- or Receiving parties are not the Buyer or Seller as stated in the Invoice document.
In such cases, it is required to identify the Buyer and the Seller as declared in the referenced Invoice.
This shall be done by giving an identifier and a name.

.UBL example:
[source, xml]
----
<cac:IssuerParty>
  <cac:PartyIdentification>
    <cbc:ID schemeID="0088">6543219876546</cbc:ID>
  </cac:PartyIdentification>
  <cac:PartyName>
    <cbc:Name>Seller company</cbc:Name>
  </cac:PartyName>
</cac:IssuerParty>
----

.UBL example:
[source, xml]
----
<cac:RecipientParty>
  <cac:PartyIdentification>
    <cbc:ID schemeID="0088">9876549873211</cbc:ID>
  </cac:PartyIdentification>
  <cac:PartyName>
    <cbc:Name>Buyer organization</cbc:Name>
  </cac:PartyName>
</cac:RecipientParty>
----
