= Calculation of VAT amounts

[[vat-calc]]
== Total VAT amount

The total VAT amount can be provided without providing the VAT breakdown, but if the VAT breakdown is present, the total VAT amount is the sum of all VAT Category VAT amounts.


====
stem:["Total VAT amount" = sum("VAT category tax amount")]
====

== VAT Breakdown

One VAT Breakdown shall be provided for each distinct combination of VAT category code and VAT rate found in either the line VAT information or the Document level allowance or charges.

For each distinct combination of VAT category code and VAT rate the calculations are:
====
stem:["VAT category taxable amount" = sum("Line net amounts")] +
stem:[+ "Document level charge amount" - "Document level allowance amount"]
====

====
stem:["VAT category tax amount" = "VAT category taxable amount" times ("VAT rate" div 100)]
====

IMPORTANT: For VAT Breakdown where the VAT Category is "Not subject to VAT" (O), the VAT category tax amount shall be zero.

Please note that for the VAT rate, only significant decimals should be considered, i.e any difference in trailing zeros should not result in different VAT breakdowns.

.Example
====
Line 1 has category code = S and VAT rate = *25* +
Line 2 has category code = S and VAT rate = *25.00* +
This should result in only one VAT Breakdown.
====

.UBL Example of tax total and tax breakdown
[source, xml, indent=0]
----
include::../../snippets/snippet-oa-vat.xml[tags=taxtotal]
----
<1> The class `cac:TaxCategory` is used for tax category information
<2> VAT category according to codelist {vat-codes}
<3> VAT rate
